---
 spring:
  datasource:
   driverClassName: com.mysql.jdbc.Driver
   url: ${cloud.services.mysql.connection.jdbcurl:jdbc:mysql://localhost/workshop_stock}
   username: ${cloud.services.mysql.connection.username:root}
   password: ${cloud.services.mysql.connection.password:root}
  jpa:
   hibernate.ddl-auto: none
   show_sql: true
   database-platform: org.hibernate.dialect.MySQLDialect