---
 spring:
  datasource:
   driverClassName: com.mysql.jdbc.Driver
   url: ${cloud.services.mysql.connection.jdbcurl:someurl1}
   username: ${cloud.services.mysql.connection.username:admin}
   password: ${cloud.services.mysql.connection.password:pass}
  jpa:
   hibernate.ddl-auto: none
   show_sql: true
   database-platform: org.hibernate.dialect.MySQLDialect